imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin/ }
    - { resource: "@MADSPosconsumosBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    
    api_name:          "Red Posconsumo API"
    api_description:   "El proyecto Backend Red Posconsumo, tiene como fin de proveer de forma centralizada, información de puntos de recolección por Programas Posconsumo. La información almacenada en bases de datos de este proyecto ha sido y/o será cargada por los responsables de las Organizaciones o Programas Posconsumo y Sistemas de Recolección Selectiva."
    
    app.path.imports_directory: %kernel.root_dir%/../web/uploads/files
    app.path.campaign_images: /uploads/images/campaigns
    app.path.waste_images: /uploads/images/waste
    app.emails_codes.confirmation: email-bienvenida
    app.emails_codes.notification_user_collectionpoint: email-notificacion-collectionpoint-usuario
    app.emails_codes.notification_user_campaign: email-notificacion-campaign-usuario

framework:
    #esi:             ~
    translator:      { fallbacks: [%locale%] }
    secret:          %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name:        "REDPOSCONSUMO"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
        - 'form/field_point.html.twig'
    globals:
        docsDir:       %kernel.root_dir%/Resources/docs/



# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%database_host%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            CampaignsTypes: MADSPosconsumosBundle\Enum\CampaignsTypes
            CollectionPointsTypes: MADSPosconsumosBundle\Enum\CollectionPointsTypes
            AppSectionsTypes: MADSPosconsumosBundle\Enum\AppSectionsTypes
            AppActionsTypes: MADSPosconsumosBundle\Enum\AppActionsTypes
            EntitiesTypes: MADSPosconsumosBundle\Enum\EntitiesTypes
            FiltersTypes: MADSPosconsumosBundle\Enum\FiltersTypes
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        # auto_mapping: true
        entity_managers:
            default:
                dql:
                    numeric_functions:
                        # numeric_functions:
                        st_contains: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                        st_makeenvelope: MADSPosconsumosBundle\doctrine\functions\STMakeEnvelope
                        contains: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Contains
                        st_area: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Area
                        st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                        st_intersects: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STIntersects
                        st_buffer: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STBuffer
                        point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    MADSPosconsumosBundle: ~
       
# File Uploader
vich_uploader:
    db_driver: orm
    mappings:
        campaign_images:
            uri_prefix: %app.path.campaign_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/campaigns
            namer: vich_uploader.namer_uniqid
        waste_images:
            uri_prefix: %app.path.waste_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/waste
            namer: vich_uploader.namer_uniqid

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MADSPosconsumosBundle\Entity\User
    # use_username_form_type: false
    service:
        mailer: mads_posconsumos.mailer.mads_twig_swift
    resetting:
        email:            
            from_email:
                address:        no-responder@minambiente.gov.co
                sender_name:    Red Posconsumo - Ministerio de Ambiente y Desarrollo Sostenible
    registration:        
        confirmation:
            enabled: true
            template: 'email/confirmation.html.twig'
            from_email:
                address:        no-responder@minambiente.gov.co
                sender_name:    Red Posconsumo - Ministerio de Ambiente y Desarrollo Sostenible


swiftmailer:
    transport:  smtp
    encryption: tls
    host:       '%mailer_host%'
    username:   '%mailer_user%'
    password:   '%mailer_password%'
    
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: es_ES
    orm:
        default:
            timestampable: true
            loggable: true

cocur_slugify:
    lowercase: true
    # regexp: <string>
    # rulesets: { }

ivory_ck_editor:
    input_sync: true
    default_config: madsbasic
    configs:
        madsbasic:
            toolbar: 
                - ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
                - ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - '/'
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt']                
                - ['Source', 'Maximize', 'ShowBlocks']
        madsfull:
            toolbar: 
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt']
                - '/'
                - ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
                - ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - ['Link', 'Unlink', 'Anchor']
                - ['Image', 'Table', 'HorizontalRule', 'SpecialChar', 'PageBreak']
                - '/'
                - ['Styles', 'Format']
                - ['Source', 'Maximize', 'ShowBlocks']

# API Platform configuration
api_platform:
    title:                             "%api_name%"
    description:                       "%api_description%"
    formats:
        jsonld:                        ['application/ld+json']
        jsonhal:                       ['application/hal+json']
        xml:                           ['application/xml', 'text/xml']
        json:                          ['application/json']
        html:                          ['text/html']
    # name_converter:                    'app.name_converter'
    enable_fos_user:                   true
    collection:
        order_parameter_name:          'order'
        order:                         'ASC'
        pagination:
            client_enabled:            true
            client_items_per_page:     true
            items_per_page:            25
    enable_nelmio_api_doc:             true

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:  ["%cors_allow_origin%"]
        allow_methods: ["POST", "GET"]
        allow_headers: ["content-type", "authorization"]
        max_age:       3600
    paths:
        '^/api': ~

# Nelmio API Doc
nelmio_api_doc:
    sandbox:
        accept_type:        "application/json"
        body_format:
            formats:        [ "json" ]
            default_format: "json"
        request_format:
            formats:
                json:       "application/json"

lexik_form_filter:
    force_case_insensitivity: false
    where_method: ~
    listeners:
        doctrine_orm: true