_homepage:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: easyadmin, permanent: true }

mads_posconsumos_admin:
    resource: "@MADSPosconsumosBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_registration_confirm:
    path: "/confirm/{token}"
    methods: "GET"
    defaults:
        _controller: FOSUserBundle:Registration:confirm

fos_user_registration_confirmed:
    path: /confirmed
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: _homepage
        permanent: true

fos_user_profile_show:
    path: /profile
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: _homepage
        permanent: true

api:
    resource: "."
    type:     "api_platform"
    prefix:   "/api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/api/doc"

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

# fos_user_profile:
#     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#     prefix: /profile

# fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: /profile
